### PR TITLE
Update IncidentIntegrationMetadataType enum

### PR DESCRIPTION
**Pull request by nikhilunni**
### What does this PR do?
We're using the new list incidents API in production, and the actual response is returning something like:
```
                  {
                     "type":"incident_integrations",
                     "id":"<id>"
                  }
```
for the `RelationshipToIncidentIntegrationMetadataData`s.

This is a draft to see if this correct, or if we're missing something. (Perhaps both enum vals are valid?)
Will add tests if it looks good.

### Review checklist
Please check relevant items below:
- [ ] This PR includes all [newly recorded cassettes](/DEVELOPMENT.md) for any modified tests.

- [ ] This PR does not rely on API client schema changes.
    - [ ] The CI should be fully passing.
- [ ] Or, this PR relies on API schema changes and this is a Draft PR that includes tests.
  - Note: CI shouldn't be run on this Draft PR, as its expected to fail without the corresponding schema changes.

### CODE REVIEW

**Comment by nikhilunni** [comment]
@zippolyte hi, does this change look correct? i can properly publish it if the API change looks good

**Comment by zippolyte** [comment]
Hi @nikhilunni 

We can't accept openapi spec contributions directly in this repo unfortunately, as it needs to be fixed in a private repo where the spec and the client generation pipeline live. I'll raise this with the team in charge of the concerned endpoint, and will update you on this thread for a fix.

For issues like this in the future, I'd advise you to open an issue only, or even better, contact our [support team](https://www.datadoghq.com/support/) directly for better tracking.

Cheers

**Comment by nikhilunni** [comment]
much appreciated!

**Comment by zippolyte** [comment]
The team made the change to our spec, I'm closing this in favour of https://github.com/DataDog/datadog-api-client-java/pull/831

Thanks for reporting

**Pull request closed without merging**
